name: Next.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install backend dependencies
        run: |
          cd API
          npm install

      - name: Install frontend dependencies
        run: |
          cd src
          npm install

      - name: Run backend
        run: |
          cd API
          npm start &
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run frontend
        run: |
          cd src
          npm run dev &
        env:
          NEXT_PUBLIC_MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Debug step
        run: |
          echo "Debugging environment..."
          env

      - name: Wait for servers to start
        run: sleep 30
