name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install mongosh
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh mongodb-org-tools

      - name: MongoDB Setup
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-version: latest

      - name: Install dependencies
        run: npm install

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Lint code
        run: npm run lint

      - name: Run Jest tests
        run: npx jest __tests__/api.test.ts

      - name: Install dependencies
        run: npm install

      - name: Start Next.js app
        run: npm run dev &

      - name: Start backend
        run: |
          npm install 
          npm start &

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
